-- create tables

create table pos_categorias (
    id                     varchar2(50 char) not null
                           constraint pos_categorias_id_pk primary key,
    nombre                 varchar2(100 char),
    descripcion            varchar2(250 char),
    activo                 varchar2(1 char) constraint pos_categorias_activo_ck
                           check (activo in ('S','N')),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_unidad_medida (
    unidad                 varchar2(45 char) not null
                           constraint pos_unidad_medida_unidad_pk primary key,
    descripcion            varchar2(100 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_tipo_atributos (
    id                     varchar2(45 char) not null
                           constraint pos_tipo_atributos_id_pk primary key,
    descripcion            varchar2(100 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_atributos (
    id                                                                         number generated by default on null as identity
                                                                               constraint pos_atributos_id_pk primary key,
    atributo                                                                   varchar2(45 char),
    tipo_atributos_id                                                          varchar2(45 char),
    descripcion                                                                varchar2(100 char),
    "constraint pos_tablatrib_pk primary key (tipo_atributos_id, atributo)"    varchar2(4000 char),
    fecha_creacion                                                             date not null,
    creado_por                                                                 varchar2(255 char) not null,
    fecha_actualizacion                                                        date not null,
    actualizado_por                                                            varchar2(255 char) not null
);



create table pos_productos (
    id                     number generated by default on null as identity
                           constraint pos_productos_id_pk primary key,
    categorias_id          varchar2(50 char)                           constraint pos_productos_categorias_id_fk
                           references pos_categorias,
    tipo_atributo1         varchar2(45 char)                           constraint pos_productos_tipo_atributo1_fk
                           references pos_tipo_atributos,
    tipo_atributo2         varchar2(45 char)                           constraint pos_productos_tipo_atributo2_fk
                           references pos_tipo_atributos,
    codigo_producto        varchar2(50 char),
    nombre                 varchar2(100 char),
    descripcion            varchar2(250 char),
    marca                  varchar2(100 char),
    imagen                 blob,
    activo                 varchar2(4000 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);

-- table index
create index pos_productos_i1 on pos_productos (categorias_id);

create index pos_productos_i2 on pos_productos (tipo_atributo1);

create index pos_productos_i3 on pos_productos (tipo_atributo2);



create table pos_subproductos (
    id                     number generated by default on null as identity
                           constraint pos_subproductos_id_pk primary key,
    productos_id           number                           constraint pos_subproductos_productos_id_fk
                           references pos_productos,
    unidad_medida          number,
    atributo1              varchar2(45 char),
    tipo_atributo1         varchar2(45 char),
    atributo2              varchar2(45 char),
    tipo_atributo2         varchar2(45 char),
    codigo_barras          varchar2(50 char),
    plu                    varchar2(50 char),
    stock                  number,
    stock_minimo           number,
    activo                 varchar2(4000 char),
    fecha_creacion         date,
    creado_por             varchar2(50 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);

-- table index
create index pos_subproductos_i1 on pos_subproductos (productos_id);

create index pos_subproductos_i2 on pos_subproductos (unidad_medida);



create table pos_"@trigger subproductos.fk_atributos1" (
    id                     number generated by default on null as identity
                           constraint pos_"@trigger subproductos.fk_atributos1"_id_pk primary key,
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_"foreign key (atributo1, tipo_atributo1) references atributos (atributo, tipo_atributos_id)" (
    id                     number generated by default on null as identity
                           constraint pos_"foreign key (atributo1, tipo_atributo1) references atributos (atributo, tipo_atributos_id)"_id_pk primary key,
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_"@trigger subproductos.fk_atributos2" (
    id                     number generated by default on null as identity
                           constraint pos_"@trigger subproductos.fk_atributos2"_id_pk primary key,
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_"foreign key (atributo2, tipo_atributo2) references atributos (atributo, tipo_atributos_id)" (
    id                     number generated by default on null as identity
                           constraint pos_"foreign key (atributo2, tipo_atributo2) references atributos (atributo, tipo_atributos_id)"_id_pk primary key,
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_precios_productos (
    id                     number generated by default on null as identity
                           constraint pos_precios_productos_id_pk primary key,
    subproductos_id        number,
    desde                  date,
    hasta                  date,
    precio                 number(12,2),
    moneda                 varchar2(10 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);

-- table index
create index pos_precios_productos_i1 on pos_precios_productos (subproductos_id);



create table pos_promociones (
    id                     number generated by default on null as identity
                           constraint pos_promociones_id_pk primary key,
    subproductos_id        number,
    desde                  date,
    hasta                  date,
    precio_producto        number(12,2),
    descripcion            varchar2(150 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);

-- table index
create index pos_promociones_i1 on pos_promociones (subproductos_id);



create table pos_usuarios (
    id                     number generated by default on null as identity
                           constraint pos_usuarios_id_pk primary key,
    nombre                 varchar2(100 char),
    correo                 varchar2(150 char),
    clave                  varchar2(255 char),
    activo                 varchar2(4000 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_roles (
    rol                    varchar2(30 char) not null
                           constraint pos_roles_rol_pk primary key,
    descripcion            varchar2(100 char),
    nivel                  number,
    activo                 varchar2(4000 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_roles_usuario (
    id                     number generated by default on null as identity
                           constraint pos_roles_usuario_id_pk primary key,
    roles_rol              number,
    usuarios_id            number,
    fecha_asignacion       date,
    asignado_por           varchar2(50 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);

-- table index
create index pos_roles_usuario_i1 on pos_roles_usuario (roles_rol);

create index pos_roles_usuario_i2 on pos_roles_usuario (usuarios_id);



create table pos_cajeros (
    id                     number generated by default on null as identity
                           constraint pos_cajeros_id_pk primary key,
    roles_usuario_id       number,
    documento              varchar2(20 char),
    telefono               varchar2(20 char),
    direccion              varchar2(150 char),
    activo                 varchar2(4000 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);

-- table index
create index pos_cajeros_i1 on pos_cajeros (roles_usuario_id);



create table pos_cajas (
    id                     number generated by default on null as identity
                           constraint pos_cajas_id_pk primary key,
    numero_caja            varchar2(4000 char),
    nombre                 varchar2(50 char),
    ubicacion              varchar2(100 char),
    estado                 varchar2(20 char),
    activo                 varchar2(4000 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_asignacion_cajas (
    id                     number generated by default on null as identity
                           constraint pos_asignacion_cajas_id_pk primary key,
    cajas_id               number,
    cajeros_id             number,
    fecha_asignacion       date,
    turno                  varchar2(20 char),
    estado_asignacion      varchar2(20 char),
    observaciones          varchar2(200 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);

-- table index
create index pos_asignacion_cajas_i1 on pos_asignacion_cajas (cajas_id);

create index pos_asignacion_cajas_i2 on pos_asignacion_cajas (cajeros_id);



create table pos_clientes (
    id                     number generated by default on null as identity
                           constraint pos_clientes_id_pk primary key,
    nombre                 varchar2(100 char),
    tipo_documento         varchar2(10 char),
    numero_documento       varchar2(30 char),
    telefono               varchar2(20 char),
    correo                 varchar2(100 char),
    direccion              varchar2(150 char),
    activo                 varchar2(4000 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_ventas (
    id                     number generated by default on null as identity
                           constraint pos_ventas_id_pk primary key,
    clientes_id            number,
    asignacion_cajas_id    number,
    fecha_venta            date,
    total_bruto            number(12,2),
    total_descuento        number(12,2),
    total_impuesto         number(12,2),
    total_neto             number(12,2),
    observaciones          varchar2(200 char),
    estado                 varchar2(20 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);

-- table index
create index pos_ventas_i1 on pos_ventas (clientes_id);

create index pos_ventas_i2 on pos_ventas (asignacion_cajas_id);



create table pos_detalle_ventas (
    id                      number generated by default on null as identity
                            constraint pos_detalle_ventas_id_pk primary key,
    ventas_id               number,
    precios_productos_id    number,
    cantidad                number(10,2),
    precio_unitario         number(12,2),
    descuento               number(12,2),
    impuesto                number(12,2),
    subtotal                number(12,2),
    fecha_creacion          date not null,
    creado_por              varchar2(255 char) not null,
    fecha_actualizacion     date not null,
    actualizado_por         varchar2(255 char) not null
);

-- table index
create index pos_detalle_ventas_i1 on pos_detalle_ventas (ventas_id);

create index pos_detalle_ventas_i2 on pos_detalle_ventas (precios_productos_id);



create table pos_formas_pago (
    id                     number generated by default on null as identity
                           constraint pos_formas_pago_id_pk primary key,
    descripcion            varchar2(100 char),
    activo                 varchar2(4000 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);



create table pos_forma_pago_ventas (
    id                     number generated by default on null as identity
                           constraint pos_forma_pago_ventas_id_pk primary key,
    formas_pago_id         number,
    ventas_id              number,
    valor_pagado           number(12,2),
    referencia_pago        varchar2(100 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);

-- table index
create index pos_forma_pago_ventas_i1 on pos_forma_pago_ventas (formas_pago_id);

create index pos_forma_pago_ventas_i2 on pos_forma_pago_ventas (ventas_id);



create table pos_cierres_diarios (
    id                     number generated by default on null as identity
                           constraint pos_cierres_diarios_id_pk primary key,
    asignacion_cajas_id    number,
    fecha_cierre           date,
    total_esperado         number(12,2),
    total_real             number(12,2),
    diferencia             number(12,2),
    observaciones          varchar2(250 char),
    estado                 varchar2(20 char),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);

-- table index
create index pos_cierres_diarios_i1 on pos_cierres_diarios (asignacion_cajas_id);



create table pos_detalle_cierre_diario (
    id                     number generated by default on null as identity
                           constraint pos_detalle_cierre_diario_id_pk primary key,
    cierres_diarios_id     number,
    formas_pago_id         number,
    valor_esperado         number(12,2),
    valor_real             number(12,2),
    diferencia             number(12,2),
    fecha_creacion         date not null,
    creado_por             varchar2(255 char) not null,
    fecha_actualizacion    date not null,
    actualizado_por        varchar2(255 char) not null
);

-- table index
create index pos_detalle_cierre_diario_i1 on pos_detalle_cierre_diario (cierres_diarios_id);

create index pos_detalle_cierre_diario_i2 on pos_detalle_cierre_diario (formas_pago_id);



alter table pos_subproductos add constraint pos_subproductos_unidad_medida_fk foreign key (unidad_medida) references pos_unidad_medida;

alter table pos_precios_productos add constraint pos_precios_productos_subproductos_id_fk foreign key (subproductos_id) references pos_subproductos.id;

alter table pos_promociones add constraint pos_promociones_subproductos_id_fk foreign key (subproductos_id) references pos_subproductos.id;

alter table pos_roles_usuario add constraint pos_roles_usuario_roles_rol_fk foreign key (roles_rol) references pos_roles.rol;

alter table pos_roles_usuario add constraint pos_roles_usuario_usuarios_id_fk foreign key (usuarios_id) references pos_usuarios.id;

alter table pos_cajeros add constraint pos_cajeros_roles_usuario_id_fk foreign key (roles_usuario_id) references pos_roles_usuario.id;

alter table pos_asignacion_cajas add constraint pos_asignacion_cajas_cajas_id_fk foreign key (cajas_id) references pos_cajas.id;

alter table pos_asignacion_cajas add constraint pos_asignacion_cajas_cajeros_id_fk foreign key (cajeros_id) references pos_cajeros.id;

alter table pos_ventas add constraint pos_ventas_clientes_id_fk foreign key (clientes_id) references pos_clientes.id;

alter table pos_ventas add constraint pos_ventas_asignacion_cajas_id_fk foreign key (asignacion_cajas_id) references pos_asignacion_cajas.id;

alter table pos_detalle_ventas add constraint pos_detalle_ventas_ventas_id_fk foreign key (ventas_id) references pos_ventas.id;

alter table pos_detalle_ventas add constraint pos_detalle_ventas_precios_productos_id_fk foreign key (precios_productos_id) references pos_precios_productos.id;

alter table pos_forma_pago_ventas add constraint pos_forma_pago_ventas_formas_pago_id_fk foreign key (formas_pago_id) references pos_formas_pago.id;

alter table pos_forma_pago_ventas add constraint pos_forma_pago_ventas_ventas_id_fk foreign key (ventas_id) references pos_ventas.id;

alter table pos_cierres_diarios add constraint pos_cierres_diarios_asignacion_cajas_id_fk foreign key (asignacion_cajas_id) references pos_asignacion_cajas.id;

alter table pos_detalle_cierre_diario add constraint pos_detalle_cierre_diario_cierres_diarios_id_fk foreign key (cierres_diarios_id) references pos_cierres_diarios.id;

alter table pos_detalle_cierre_diario add constraint pos_detalle_cierre_diario_formas_pago_id_fk foreign key (formas_pago_id) references pos_formas_pago.id;

-- triggers
create or replace trigger pos_categorias_biu
    before insert or update
    on pos_categorias
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_categorias_biu;
/


create or replace trigger pos_unidad_medida_biu
    before insert or update
    on pos_unidad_medida
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_unidad_medida_biu;
/


create or replace trigger pos_tipo_atributos_biu
    before insert or update
    on pos_tipo_atributos
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_tipo_atributos_biu;
/


create or replace trigger pos_atributos_biu
    before insert or update
    on pos_atributos
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_atributos_biu;
/


create or replace trigger pos_productos_biu
    before insert or update
    on pos_productos
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_productos_biu;
/


create or replace trigger pos_subproductos_biu
    before insert or update
    on pos_subproductos
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_subproductos_biu;
/


create or replace trigger pos_"@trigger subproductos.fk_atributos1"_biu
    before insert or update
    on pos_"@trigger subproductos.fk_atributos1"
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_"@trigger subproductos.fk_atributos1"_biu;
/


create or replace trigger pos_"foreign key (atributo1, tipo_atributo1) references atributos (atributo, tipo_atributos_id)"_biu
    before insert or update
    on pos_"foreign key (atributo1, tipo_atributo1) references atributos (atributo, tipo_atributos_id)"
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_"foreign key (atributo1, tipo_atributo1) references atributos (atributo, tipo_atributos_id)"_biu;
/


create or replace trigger pos_"@trigger subproductos.fk_atributos2"_biu
    before insert or update
    on pos_"@trigger subproductos.fk_atributos2"
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_"@trigger subproductos.fk_atributos2"_biu;
/


create or replace trigger pos_"foreign key (atributo2, tipo_atributo2) references atributos (atributo, tipo_atributos_id)"_biu
    before insert or update
    on pos_"foreign key (atributo2, tipo_atributo2) references atributos (atributo, tipo_atributos_id)"
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_"foreign key (atributo2, tipo_atributo2) references atributos (atributo, tipo_atributos_id)"_biu;
/


create or replace trigger pos_precios_productos_biu
    before insert or update
    on pos_precios_productos
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_precios_productos_biu;
/


create or replace trigger pos_promociones_biu
    before insert or update
    on pos_promociones
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_promociones_biu;
/


create or replace trigger pos_usuarios_biu
    before insert or update
    on pos_usuarios
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_usuarios_biu;
/


create or replace trigger pos_roles_biu
    before insert or update
    on pos_roles
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_roles_biu;
/


create or replace trigger pos_roles_usuario_biu
    before insert or update
    on pos_roles_usuario
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_roles_usuario_biu;
/


create or replace trigger pos_cajeros_biu
    before insert or update
    on pos_cajeros
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_cajeros_biu;
/


create or replace trigger pos_cajas_biu
    before insert or update
    on pos_cajas
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_cajas_biu;
/


create or replace trigger pos_asignacion_cajas_biu
    before insert or update
    on pos_asignacion_cajas
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_asignacion_cajas_biu;
/


create or replace trigger pos_clientes_biu
    before insert or update
    on pos_clientes
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_clientes_biu;
/


create or replace trigger pos_ventas_biu
    before insert or update
    on pos_ventas
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_ventas_biu;
/


create or replace trigger pos_detalle_ventas_biu
    before insert or update
    on pos_detalle_ventas
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_detalle_ventas_biu;
/


create or replace trigger pos_formas_pago_biu
    before insert or update
    on pos_formas_pago
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_formas_pago_biu;
/


create or replace trigger pos_forma_pago_ventas_biu
    before insert or update
    on pos_forma_pago_ventas
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_forma_pago_ventas_biu;
/


create or replace trigger pos_cierres_diarios_biu
    before insert or update
    on pos_cierres_diarios
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_cierres_diarios_biu;
/


create or replace trigger pos_detalle_cierre_diario_biu
    before insert or update
    on pos_detalle_cierre_diario
    for each row
begin
    if inserting then
        :new.fecha_creacion := sysdate;
        :new.creado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.fecha_actualizacion := sysdate;
    :new.actualizado_por := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end pos_detalle_cierre_diario_biu;
/


-- Generated by Quick SQL 1.2.9 29/3/2025, 10:02:18

/*
-- CATEGORÍAS Y PRODUCTOS
categorias
  id vc50 /pk 
  nombre vc(100)
  descripcion vc(250)
  activo vc(1) default 'S' /check 'S','N'
 
unidad_medida
  unidad vc(45) /pk
  descripcion vc(100)

tipo_atributos
  id vc(45) /pk
  descripcion vc(100)

atributos
  atributo vc(45) 
  tipo_atributos_id vc(45) 
  descripcion vc(100)
  constraint pos_tablatrib_pk primary key (tipo_atributos_id, atributo)

productos
  id number /pk
  categorias_id vc50 /fk categorias
  codigo_producto vc50
  nombre vc(100)
  descripcion vc(250)
  marca vc(100)
  imagen blob
  activo char(1) default 'S'
  tipo_atributo1 /fk tipo_atributos
  tipo_atributo2 /fk tipo_atributos
 


subproductos
  id number /pk
  productos_id number /fk productos
  unidad_medida vc(45) /fk unidad_medida
  atributo1 vc(45)
  tipo_atributo1 vc(45)
  atributo2 vc(45)
  tipo_atributo2 vc(45)
  codigo_barras vc(50)
  plu vc50
  stock number default 0
  stock_minimo number default 0
  activo char(1) default 'S'
  fecha_creacion date
  creado_por vc(50)

--Crear relaciones para claves compuestas después de definir las tablas
@trigger subproductos.fk_atributos1
foreign key (atributo1, tipo_atributo1) references atributos (atributo, tipo_atributos_id)

@trigger subproductos.fk_atributos2
foreign key (atributo2, tipo_atributo2) references atributos (atributo, tipo_atributos_id)

precios_productos
  id number /pk
  desde date
  hasta date
  precio number(12,2)
  subproductos_id number /fk subproductos.id
  moneda vc(10) default 'COP'


promociones
  id number /pk
  subproductos_id number /fk subproductos.id
  desde date
  hasta date
  precio_producto number(12,2)
  descripcion vc(150)


-- ADMINISTRACIÓN Y USUARIOS
usuarios
  id number /pk
  nombre vc(100)
  correo vc(150)
  clave vc(255)
  activo char(1) default 'S'


roles
  rol vc(30) /pk
  descripcion vc(100)
  nivel number
  activo char(1) default 'S'

roles_usuario
  id number /pk
  roles_rol vc(30) /fk roles.rol
  usuarios_id number /fk usuarios.id
  fecha_asignacion date
  asignado_por vc(50)

cajeros
  id number /pk
  roles_usuario_id number /fk roles_usuario.id
  documento vc(20)
  telefono vc(20)
  direccion vc(150)
  activo char(1) default 'S'


cajas
  id number /pk
  numero_caja num
  nombre vc(50)
  ubicacion vc(100)
  estado vc(20) default 'Disponible'
  activo char(1) default 'S'


asignacion_cajas
  id number /pk
  cajas_id number /fk cajas.id
  cajeros_id number /fk cajeros.id
  fecha_asignacion date
  turno vc(20)
  estado_asignacion vc(20) default 'Activa'
  observaciones vc(200)

-- VENTAS
clientes
  id number /pk
  nombre vc(100)
  tipo_documento vc(10)
  numero_documento vc(30)
  telefono vc(20)
  correo vc(100)
  direccion vc(150)
  activo char(1) default 'S'

ventas
  id number /pk
  clientes_id number /fk clientes.id
  asignacion_cajas_id number /fk asignacion_cajas.id
  fecha_venta date default sysdate
  total_bruto number(12,2)
  total_descuento number(12,2)
  total_impuesto number(12,2)
  total_neto number(12,2)
  observaciones vc(200)
  estado vc(20) default 'Completada'


detalle_ventas
  id number /pk
  ventas_id number /fk ventas.id
  precios_productos_id number /fk precios_productos.id
  cantidad number(10,2)
  precio_unitario number(12,2)
  descuento number(12,2)
  impuesto number(12,2)
  subtotal number(12,2)

formas_pago
  id number /pk
  descripcion vc(100)
  activo char(1) default 'S'

forma_pago_ventas
  id number /pk
  formas_pago_id number /fk formas_pago.id
  ventas_id number /fk ventas.id
  valor_pagado number(12,2)
  referencia_pago vc(100)

-- CIERRES DE CAJA
cierres_diarios
  id number /pk
  asignacion_cajas_id number /fk asignacion_cajas.id
  fecha_cierre date default sysdate
  total_esperado number(12,2)
  total_real number(12,2)
  diferencia number(12,2)
  observaciones vc(250)
  estado vc(20) default 'Pendiente'


detalle_cierre_diario
  id number /pk
  cierres_diarios_id number /fk cierres_diarios.id
  formas_pago_id number /fk formas_pago.id
  valor_esperado number(12,2)
  valor_real number(12,2)
  diferencia number(12,2)

 Non-default options:
# settings = {"apex":"Y","auditcols":"Y","createdcol":"fecha_creacion","createdbycol":"creado_por","updatedcol":"fecha_actualizacion","updatedbycol":"actualizado_por","db":"21c","prefix":"pos","pk":"IDENTITY"}

*/